version: '3'
volumes:
  node_modules:

services:
  client:
    build: ./client
    image: containous-codetest-client
    container_name: containous-codetest-client
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    depends_on:
      - server
    labels:
      - traefik.enable=true
      - "traefik.http.routers.client.rule=Host(`codetest.localhost`)"
      - "traefik.http.routers.client.entrypoints=web"

  server:
    build: ./server
    image: containous-codetest-server
    container_name: containous-codetest-server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003
    labels:
      - traefik.enable=true
      - "traefik.http.routers.server.rule=Host(`api.codetest.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"

  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
